version: '3.1'

services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kotlin_boot
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
      MYSQL_TCP_PORT: 3307
    volumes:
      - "./mysql_data:/var/lib/mysql"
      - "./src/main/resources/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro"
    expose:
      - 3307