
### Post "book!"
POST http://localhost:8080/api/books
Content-Type: application/json

{
    "title": "Also Sprach Zarathustra",
    "isbn": "1234567891",
    "pages": 959
}

### Add author
POST http://localhost:8080/api/books/102443001606832128/authors
Content-Type: application/json

{
    "authorId": 7
}






