
### Post "Hello!"
POST http://localhost:8080/books
Content-Type: application/json

{
    "title": "Also Sprach Zarathustra",
    "isbn": "9781452602561",
    "pages": 959,
    "authorId": 1
}

### Post "Bonjour!"
DELETE http://localhost:8080/books/100918099238191104

### Post "Privet!"
POST http://localhost:8080
Content-Type: application/json

{
    "text": "Privet!"
}

### get all the messages
GET http://localhost:8080/






