spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/kotlin_boot
    username: admin
    password: pass
  jooq:
    sql-dialect: mysql
  sql:
    init:
      mode: never

logging.level:
  root: info
  org:
    jooq.Constants.level: warn
    springframework:
      jdbc.core.JdbcTemplate: DEBUG
