spring.datasource.driver-class-name: org.mariadb.jdbc.Driver
spring.datasource.url: jdbc:mariadb://localhost:3306/kotlin_boot
spring.datasource.username: root
spring.datasource.password: root
spring.datasource.schema: classpath:sql/schema.sql
spring.datasource.initialization-mode: always
spring:
  jooq:
    sql-dialect: mariadb

logging.level:
  root: debug
  org:
    jooq.Constants.level: warn
    springframework:
      jdbc.core.JdbcTemplate: DEBUG
