spring.datasource.driver-class-name: org.mariadb.jdbc.Driver
spring.datasource.url: jdbc:mariadb://localhost:3306/kotlin_boot
spring.datasource.username: root
spring.datasource.password: root
spring.datasource.schema: classpath:sql/schema.sql
spring.datasource.initialization-mode: always
